name: Run pylint and upload badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run pylint and generate badge
    runs-on: ubuntu-latest  # Only Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Python 3.10 only

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Install pylint and anybadge
        run: |
          pip install pylint anybadge

      - name: Install Psychos
        run: |
          pip install .

      - name: Run pylint on the 'psychos' folder and print output, ignoring R0913, R0914, R0917
        run: |
          pylint psychos --exit-zero --disable=R0902,R0913,R0914,R0917 --output-format=colorized | tee pylint_output.txt

      - name: Generate pylint badge with anybadge
        run: |
          pylint_score=$(pylint psychos --fail-under=0 --exit-zero --disable=R0902,R0913,R0914,R0917 --score=y | grep "Your code has been rated" | awk '{print $7}' | tr -d '/10')
          anybadge --value=$pylint_score --label="pylint" --file=pylint_badge.svg 2=red 8=orange 9=yellow 10=green

      - name: Upload pylint badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pylint-badge
          path: pylint_badge.svg

      - name: Upload pylint output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pylint-output
          path: pylint_output.txt
